/* BEGIN_LEGAL 

Copyright (c) 2025 Intel Corporation

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
  
END_LEGAL */
/// @file xed-operand-convert-enum.h

// This file was automatically generated.
// Do not edit this file.

#if !defined(XED_OPERAND_CONVERT_ENUM_H)
# define XED_OPERAND_CONVERT_ENUM_H
#include "xed-common-hdrs.h"
#define XED_OPERAND_CONVERT_INVALID_DEFINED 1
#define XED_OPERAND_CONVERT_ZEROSTR_DEFINED 1
#define XED_OPERAND_CONVERT_SAESTR_DEFINED 1
#define XED_OPERAND_CONVERT_ROUNDC_DEFINED 1
#define XED_OPERAND_CONVERT_BCASTSTR_DEFINED 1
#define XED_OPERAND_CONVERT_MULTIREG_START_DEFINED 1
#define XED_OPERAND_CONVERT_MULTIREG2_DEFINED 1
#define XED_OPERAND_CONVERT_MULTIREG3_DEFINED 1
#define XED_OPERAND_CONVERT_MULTIREG4_DEFINED 1
#define XED_OPERAND_CONVERT_MULTIREG5_DEFINED 1
#define XED_OPERAND_CONVERT_MULTIREG6_DEFINED 1
#define XED_OPERAND_CONVERT_MULTIREG7_DEFINED 1
#define XED_OPERAND_CONVERT_MULTIREG8_DEFINED 1
#define XED_OPERAND_CONVERT_MULTIREG9_DEFINED 1
#define XED_OPERAND_CONVERT_MULTIREG10_DEFINED 1
#define XED_OPERAND_CONVERT_MULTIREG11_DEFINED 1
#define XED_OPERAND_CONVERT_MULTIREG12_DEFINED 1
#define XED_OPERAND_CONVERT_MULTIREG13_DEFINED 1
#define XED_OPERAND_CONVERT_MULTIREG14_DEFINED 1
#define XED_OPERAND_CONVERT_MULTIREG15_DEFINED 1
#define XED_OPERAND_CONVERT_MULTIREG16_DEFINED 1
#define XED_OPERAND_CONVERT_LAST_DEFINED 1
typedef enum {
  XED_OPERAND_CONVERT_INVALID,
  XED_OPERAND_CONVERT_ZEROSTR,
  XED_OPERAND_CONVERT_SAESTR,
  XED_OPERAND_CONVERT_ROUNDC,
  XED_OPERAND_CONVERT_BCASTSTR,
  XED_OPERAND_CONVERT_MULTIREG_START,
  XED_OPERAND_CONVERT_MULTIREG2,
  XED_OPERAND_CONVERT_MULTIREG3,
  XED_OPERAND_CONVERT_MULTIREG4,
  XED_OPERAND_CONVERT_MULTIREG5,
  XED_OPERAND_CONVERT_MULTIREG6,
  XED_OPERAND_CONVERT_MULTIREG7,
  XED_OPERAND_CONVERT_MULTIREG8,
  XED_OPERAND_CONVERT_MULTIREG9,
  XED_OPERAND_CONVERT_MULTIREG10,
  XED_OPERAND_CONVERT_MULTIREG11,
  XED_OPERAND_CONVERT_MULTIREG12,
  XED_OPERAND_CONVERT_MULTIREG13,
  XED_OPERAND_CONVERT_MULTIREG14,
  XED_OPERAND_CONVERT_MULTIREG15,
  XED_OPERAND_CONVERT_MULTIREG16,
  XED_OPERAND_CONVERT_LAST
} xed_operand_convert_enum_t;

/// This converts strings to #xed_operand_convert_enum_t types.
/// @param s A C-string.
/// @return #xed_operand_convert_enum_t
/// @ingroup ENUM
XED_DLL_EXPORT xed_operand_convert_enum_t str2xed_operand_convert_enum_t(const char* s);
/// This converts strings to #xed_operand_convert_enum_t types.
/// @param p An enumeration element of type xed_operand_convert_enum_t.
/// @return string
/// @ingroup ENUM
XED_DLL_EXPORT const char* xed_operand_convert_enum_t2str(const xed_operand_convert_enum_t p);

/// Returns the last element of the enumeration
/// @return xed_operand_convert_enum_t The last element of the enumeration.
/// @ingroup ENUM
XED_DLL_EXPORT xed_operand_convert_enum_t xed_operand_convert_enum_t_last(void);
#endif
